<div id="<?php echo $widgetId; ?>"
     class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params)?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer MessagesWidget">
        <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/><small><?php echo $params['subtitle']; ?></small><?php endif?></h1>

        <% _.each(value, function(item) { %>
            <div class="message row-fluid">
                <div class="span12 last">
                    <div class="content">
                        <span class="failure">
                            <strong><%= item.url %></strong><br/><small> <%= item.numberOfErrors %> errors, last at <% var date = new Date(item.lastErrorTime*1000); print(date.getUTCFullYear() + '-' +
                                    ('00' + (date.getUTCMonth()+1)).slice(-2) + '-' +
                                    ('00' + date.getUTCDate()).slice(-2) + ' ' +
                                    ('00' + date.getUTCHours()).slice(-2) + ':' +
                                    ('00' + date.getUTCMinutes()).slice(-2) + ':' +
                                    ('00' + date.getUTCSeconds()).slice(-2)) %></small>
                        </span>
                    </div>
                </div>

            </div>
        <% }); %>

        <p class="updated-at">Last update: <%= lastUpdate %></p>
    </div>
</script>
