<div id="<?php echo $widgetId; ?>"
     class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>">
    <div class="widgetContainer">
        <h1 class="buildName"><?php echo $params['title']; ?></h1>

        <span class="currentStatus"></span>

        <div class="averageHealthScore"></div>
        <span class="lastCommitter"></span>
        <span class="percentDone"></span>
        Last build at <span class="lastBuilt"></span>
    </div>
</div>