<div id="<?php echo $this->widgetId; ?>" class="span<?php echo $params['span']; ?> widget <?php echo $this->widgetType; ?>">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?></h1>

        <h2 class="value" data-sufix="<?php echo $params['valueSufix']; ?>"
            data-prefix="<?php echo $params['valuePrefix']; ?>"></h2>
        <p class="change-rate">
            <i class="icon-arrow-up"></i>
            <span class="difference"></span>
        </p>

        <p class="updated-at"></p>
    </div>
</div>