<div id="<?php echo $widgetId; ?>" class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>">
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?></h1>

        <p><%= currentStatus %></p>
        <p><%= averageHealthScore %></div>
        <p><%= lastCommitter %></p>
        <p><%= percentDone %></p>
        <p><%= lastBuilt %></p>

    </div>
</script>