<div id="<?php echo $widgetId; ?>"
     class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params)?>'
     data-threshold-caution-value="<?php echo isset($threshold['caution-value']) ? $threshold['caution-value'] : 0?>"
     data-threshold-critical-value="<?php echo isset($threshold['critical-value']) ? $threshold['critical-value'] : 0?>">
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/><small><?php echo $params['subtitle']; ?></small><?php endif?></h1>

        <h2 class="value">
            <span class="prefix"><?php echo $params['valuePrefix']; ?></span><%= value %><span
                class="suffix"><?php echo $params['valueSuffix']; ?></span></h2>
        <p class="sock"></p>
        <p class="updated-at">Last update: <%= lastUpdate %></p>
    </div>
</script>