<div id="<?php echo $widgetId; ?>"
     class="col-md-<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'
     data-threshold-caution-value="<?php echo isset($threshold['caution-value']) ? $threshold['caution-value'] : 0 ?>"
     data-threshold-critical-value="<?php echo isset($threshold['critical-value']) ? $threshold['critical-value'] : 0 ?>">
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/>
                <small><?php echo $params['subtitle']; ?></small><?php endif?>
        </h1>
            <div class="processes">
                <% _.each(value.result.subtree[0].subtree[0].subtree, function(process) { %>
                <table class="process <%= process.state %>">
                    <tr>
                        <th class="name"><%= process.name %></th>
                        <td class="state">
                            <%= process.state %> since <%= new Date(process.state_changed_at * 1000).toLocaleDateString() %> <%= new Date(process.state_changed_at * 1000).toLocaleTimeString() %> <br/>
                            <span class="resources">
                                CPU: <%= process.resources.cpu %> <span class="delimiter">|</span>
                                RAM: <%= Math.round(process.resources.memory/1024/1024) %>MB
                            </span>
                        </td>
                    </tr>
                </table>
                <% }); %>
            </div>

        <p class="updated-at">Last update: <%= lastUpdate %></p>
    </div>
</script>
