<div id="<?php echo $widgetId; ?>" class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>" data-params='<?php echo $this->json($params)?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h3><?php echo $params['title']?></h3>
        <% _.each(value, function(item) { %>
            <div class="message">
                <p class="createdAt"><%= item.createdAt %><% if (item.projectName != '') {%> <span class="label label-info"><%= item.projectName %></span><% } %></p>
                <p class="content"><%= item.content %></p>
            </div>
        <% }); %>

    </div>
</script>
