<div id="<?php echo $widgetId; ?>" class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>" data-params='<?php echo $this->json($params)?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h3><?php echo $params['title']?></h3>
        <% _.each(value, function(item) { %>
            <div class="message">
                <div class="content row-fluid"><%= item.content %></div>
                <div class="createdAt"><% if (item.projectName != '') {%><span class="label label-info"><%= item.projectName %></span> <% } %><%= item.createdAt %></div>
            </div>
        <% }); %>

    </div>
</script>
