<div id="<?php echo $widgetId; ?>"
     class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params)?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <div class="text">
            <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/><small><?php echo $params['subtitle']; ?></small><?php endif?></h1>

            <h2 class="value">
                <span class="prefix"><?php echo $params['valuePrefix']; ?></span><%= value %><span
                    class="suffix"><?php echo $params['valueSuffix']; ?></span></h2>

            <% if (percentageDiff > 0) { %>
            <p class="change-rate">
                <i class="<%= arrowClass %>"></i>
                <span class="difference"><%= percentageDiff %>% (<%= oldValue %><?php echo $params['valueSuffix']; ?>)</span>
            </p>
            <% } %>
        </div>

        <div class="graph_container">
            <div class="graph"></div>
        </div>
    </div>
</script>