<div id="<?php echo $widgetId; ?>"
     class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?><br/>
            <small><%= name  %></small>
        </h1>

        <div class="content <%= className %>">
            <i class="<%= icon %>"></i>
            <div class="heroku-message"><%= message %></div>
        </div>
    </div>
</script>
