<div id="<?php echo $widgetId; ?>"
     class="col-md-<?php echo $params['span']; ?> widget <?php echo $widgetType; ?> GraphWidget"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <div class="text">
            <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/>
                <small><?php echo $params['subtitle']; ?></small><?php endif?>
            </h1>

            <h2 class="value">
                <span class="prefix"><?php echo $params['valuePrefix']; ?></span><span
                class="content"><%= value %></span><span class="suffix"><?php echo $params['valueSuffix']; ?></span>
            </h2>

            <p class="change-rate">
                <i class="icon-arrow"></i>
                <span class="difference"><span class="percentageDiff"></span>% (<span
                    class="old-value"></span><?php echo $params['valueSuffix']; ?>)</span>
            </p>
        </div>

        <div class="graph_container">
            <div class="graph"></div>
        </div>
    </div>
</script>
