<div id="<?php echo $widgetId; ?>"
     class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?></h1>


<h5>Latest activities:</h5>
<div class="message hide">
    <p class="createdAt"></p>
    <p class="content"></p>
</div>        <div class="message hidden">
            <p class="createdAt"></p>

            <p class="content"></p>
        </div>
    </div>
</div>
