<div id="<?php echo $widgetId; ?>" class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>">
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?></h1>

        <h5>Latest activities:</h5>
        <% _.each(value, function(item) { %>
            <div class="message">
                <p class="createdAt"><%= item.createdAt %></p>
                <p class="content"><%= item.content %></p>
            </div>
        <% }); %>

    </div>
</script>
