<div id="<?php echo $widgetId; ?>" class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>" data-params='<?php echo $this->json($params)?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?> Latest Activities<?php if ($params['subtitle']):?><br/><small><?php echo $params['subtitle']; ?></small><?php endif?></h1>

        <% _.each(value, function(item) { %>
            <div class="message row-fluid">
                <% if (item.avatar) {%>
                    <div class="span2 targetAvatar">
                        <%= item.avatar %>
                    </div>
                    <div class="span10 last">
                        <div class="content"><%= item.content %></div>
                        <div class="createdAt"><% if (item.projectName != '') {%><span class="label label-info"><%= item.projectName %></span> <% } %><%= item.createdAt %></div>
                    </div>
                <%} else {%>
                    <div class="span12 last">
                        <div class="content"><%= item.content %></div>
                        <div class="createdAt"><% if (item.projectName != '') {%><span class="label label-info"><%= item.projectName %></span> <% } %><%= item.createdAt %></div>
                    </div>
                <% } %>
            </div>
        <% }); %>
    </div>
</script>
