<div id="<?php echo $widgetId; ?>" class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>" data-params='<?php echo $this->json($params)?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/><small><?php echo $params['subtitle']; ?></small><?php endif?></h1>

        <h2 class="value">
            <span class="prefix"><?php echo $params['valuePrefix']; ?></span><%= value %><span
                class="sufix"><?php echo $params['valueSufix']; ?></span></h2>

        <p class="change-rate<%= visibilityClass %>">
            <i class="<%= arrowClass %>"></i>
            <span class="difference"><%= difference %></span>
        </p>

        <p class="updated-at">Last update: <%= lastUpdate %></p>
    </div>
</script>