<div id="<?php echo $widgetId; ?>"
     class="col-md-<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'
     data-threshold-caution-value="<?php echo isset($threshold['caution-value']) ? $threshold['caution-value'] : 0 ?>"
     data-threshold-critical-value="<?php echo isset($threshold['critical-value']) ? $threshold['critical-value'] : 0 ?>">
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/>
                <small><?php echo $params['subtitle']; ?></small><?php endif?>
        </h1>
            <div class="process <%= value.statename %>">
                <tr>
                    <% if (value.statename == 'RUNNING') {%>
                        <i class="icon icon-thumbs-up"></i>
                    <% } else if (value.statename == 'STARTING')  { %>
                        <i class="icon icon-refresh"></i>
                    <% } else { %>
                        <i class="icon icon-thumbs-down"></i>
                    <% } %>

                    <div class="pid">
                        PID: <%=value.pid%>
                    </div>
                    <div class="state">
                        <%= value.statename %><br/> since <% print(new Date(value.start * 1000).format('Y-m-d H:i:s'))%><br/>
                    </div>
                </tr>
            </div>

        <p class="updated-at">Last update: <%= lastUpdate %></p>
    </div>
</script>
