<div id="<?php echo $widgetId; ?>"
     class="span<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'
     data-threshold-caution-value="<?php echo isset($threshold['caution-value']) ? $threshold['caution-value'] : 0 ?>"
     data-threshold-critical-value="<?php echo isset($threshold['critical-value']) ? $threshold['critical-value'] : 0 ?>">
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/>
                <small><?php echo $params['subtitle']; ?></small><?php endif?>
        </h1>
        <% _.each(value.result.subtree, function(process) {%>
            <div class="process <%= process.state %>">
                <tr>
                    <% if (process.state == 'up') {%>
                        <i class="icon icon-thumbs-up"></i>
                    <% } else if (process.state == 'starting')  { %>
                        <i class="icon icon-refresh"></i>
                    <% } else { %>
                        <i class="icon icon-thumbs-down"></i>
                    <% } %>
                    <div class="name"><span class="pid">PID: <%= process.resources.pid %></span></div>
                    <div class="state">
                        <%= process.state %> since <% print(new Date(process.state_changed_at * 1000).format('Y-m-d H:i:s'))%><br/>
                        <span class="resources">
                            CPU: <%= process.resources.cpu %> <span class="delimiter">|</span>
                            RAM: <%= Math.round(process.resources.memory/1024/1024) %>MB
                        </span>
                    </div>
                </tr>
            </div>
        <% }); %>

        <p class="updated-at">Last update: <%= lastUpdate %></p>
    </div>
</script>
