<div id="<?php echo $widgetId; ?>"
     class="col-md-<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'
     data-threshold-caution-value="<?php echo isset($threshold['caution-value']) ? $threshold['caution-value'] : 0 ?>"
     data-threshold-critical-value="<?php echo isset($threshold['critical-value']) ? $threshold['critical-value'] : 0 ?>">
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <img src="http://2600hz.org/images/rabbitmq.png" class="logo"/>

            <div class="queues">
                <% _.each(value, function(queue) { %>
                <table class="queue">
                <tr>
                    <th class="name <%= queue.status %>"><%= queue.name %></th>
                    <% if (!_.isUndefined(queue.messages)) { %>
                        <td class="status">
                            <span class="<%= queue.messages > 0 ? "warning" : "success" %>">
                                <%= queue.messages %> msgs</span> (<%= queue.messages_details.rate %>/s)
                            <span class="<%= queue.consumers > 0 ? "success" : "failure" %>"><%= queue.consumers %> workers</span>
                        </td>
                    <% } else { %>
                        <td class="status">
                        <span class=success">
                            0 messages</span>
                            <span class="<%= queue.consumers > 0 ? "success" : "failure" %>"><%= queue.consumers %> workers</span>
                        </td>
                    <% } %>
                </tr>


                </table>
                <% }); %>
            </div>

        <p class="updated-at">Last update: <%= lastUpdate %></p>
    </div>
</script>
