<div id="<?php echo $widgetId; ?>"
     class="col-md-<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?> Latest Activities<?php if ($params['subtitle']):?><br/>
            <small><?php echo $params['subtitle']; ?></small><?php endif?>
        </h1>


        <% _.each(value, function(item) { %>
            <div class="message row">
                <div class="col-md-12 last">
                    <img src="<%= item.user.avatar %>" class="avatar"/>

                    <div class="content">
                        <%= item.text %>
                        <% _.each(item.attachments, function(attachment) { %>
                            <%= attachment.fallback %>
                        <% }); %>
                    </div>
                    <div class="createdAt"><% if (item.projectName != '') {%><span
                        class="label label-info"><%= item.projectName %></span> <% } %><%= item.createdAt %></div>
                </div>
            </div>

        <% }); %>
    </div>
</script>
