<div id="<?php echo $widgetId; ?>"
     class="col-md-<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <div class="text">
            <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/>
                <small><?php echo $params['subtitle']; ?></small><?php endif?>
            </h1>
        </div>

        <div class="graph_container">
            <div class="graph"></div>
        </div>
    </div>
</script>
