<div id="<?php echo $widgetId; ?>"
     class="col-md-<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer MessagesWidget">
        <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/>
            <small><?php echo $params['subtitle']; ?></small><?php endif?>
        </h1>


        <table class="content">


            <% _.each(value, function(item) { %>
            <tr>
                <td class="item-name"><%= item.name %></td>
                <td class="item-value"><%= item.value %></td>
            </tr>
            <% }); %>


        </table>


        <p class="updated-at">Last update: <%= lastUpdate %></p>
    </div>
</script>
