<div id="<?php echo $widgetId; ?>"
     class="col-md-<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params) ?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <h1 class="title"><?php echo $params['title']; ?><br/>
                <small><%= name  %></small>
        </h1>

        <div class="content">
            <div class="weather-icon"><%= icon %></div>
            <div class="weather-info">
                <%= temperature %> &deg;C
            </div>
        </div>
    </div>
</script>
