<?php
$span = 0;
$i = 0;

/* @var $widget Dashboard\Model\Widget\AbstractWidget */
foreach ($this->widgets as $widget) {
    $span += $widget->getParam('span');
    if ($span > 12) {
        echo '</div><div class="row-fluid">';
        $span = $widget->getParam('span');;
    }

    echo $this->partial($widget->getTplName(), array(
            'widgetId' => $widget->getId(),
            'widgetType' => $widget->getClassName(),
            'params' => $widget->getParams())
    );
}