<?php
/**
 * Config for rtm
 */
return array(
    'rabbitMQ' => array(
        'params' => array(
            'rabbitMQUrl' => 'http://vg-dev-01:15672',
            'vhost' => 'integrator',
        ),
        'headers' => array(
            'X-Requested-With' => 'XMLHttpRequest',
        ),
        'auth' => array(
            'username' => 'integrator',
            'password' => 'gBjBkeup',
        ),
    ),
    'hipChat' => array(
        'params' => array(
            'auth_token' => 'd5e182ac9d356cbc72b9f9c2fc119f',
        ),
    ),
    'eye' => array(
        'params' => array(
            'eyeUrl' => 'http://integrator-cron-s01.int.vgnett.no:6937',
        ),
    ),
    'jenkins' => array(
        'params' => array(
            'baseUrl' => 'http://ci.vgnett.no/',
        ),
    ),
    'widgets' => array(
        array('id' => 'integratorCrawlersBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-crawlers',
                'metric' => 'status',
                'title' => 'Crawlers',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorWritersBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-writers',
                'metric' => 'status',
                'title' => 'Writers',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'messagesIntegrator',
            'type' => 'messages',
            'params' => array(
                'dao' => 'hipChat',
                'metric' => 'listRecentMessages',
                'span' => 6,
                'subtitle' => '',
                'title' => 'Integrator',
                'limit' => 10,
                'room' => '678235',
                'refreshRate' => 30,
                'fromUser' => ['jenkins', 'Cap4All'],
            ),
        ),
        array('id' => 'integratorNewsletterSubscriptionsBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-newsletter-subscriptions',
                'metric' => 'status',
                'title' => 'Subscriptions',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorNewsletterSubscriptionsIntegrationBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-newsletter-subscriptions-integration',
                'metric' => 'status',
                'title' => 'Subscriptions integration',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorRabbitMQQueues',
            'type' => 'rabbitMQ',
            'params' => array(
                'dao' => 'rabbitMQ',
                'metric' => 'queues',
                'title' => 'RabbitMQ',
                'span' => 6,
                'ignoreQueues' => ['.*testing.*', '.*:invalid:.*'],
                'queueNameParser' => function($queueName) { return str_replace(':queue', '', str_replace('integrator:', '', $queueName));},
            ),
        ),
        array('id' => 'integratorEyeProcesses',
            'type' => 'eye',
            'params' => array(
                'dao' => 'eye',
                'metric' => 'info',
                'title' => 'Eye processes',
                'span' => 6,
            ),
        ),
        array('id' => 'integratorCleanAdobeCampaignProcess',
            'type' => 'process',
            'params' => array(
                'dao' => 'eye',
                'metric' => 'info',
                'title' => 'Clean Adobe Campaign',
                'processName' => 'clean_adobe_campaign',
            ),
        ),
        array('id' => 'integratorRawHadoopMessages',
            'type' => 'graph',
            'params' => array(
                'dao' => 'rabbitMQ',
                'metric' => 'queuedMessages',
                'title' => 'Hadoop RAW',
                'span' => 3,
                'queueName' => 'integrator:raw:hadoop:queue',
                'secondsBack' => '1200',
                'secondsIntervals' => '5',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorCleanHadoopMessages',
            'type' => 'graph',
            'params' => array(
                'dao' => 'rabbitMQ',
                'metric' => 'queuedMessages',
                'title' => 'Hadoop CLEAN',
                'span' => 3,
                'queueName' => 'integrator:clean:hadoop:queue',
                'secondsBack' => '1200',
                'secondsIntervals' => '5',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorCleanMysqlMessages',
            'type' => 'graph',
            'params' => array(
                'dao' => 'rabbitMQ',
                'metric' => 'queuedMessages',
                'title' => 'MySQL',
                'span' => 3,
                'queueName' => 'integrator:clean:mysql:queue',
                'secondsBack' => '1200',
                'secondsIntervals' => '5',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorCleanAdobeCampaignMessages',
            'type' => 'graph',
            'params' => array(
                'dao' => 'rabbitMQ',
                'metric' => 'queuedMessages',
                'title' => 'Adobe Campaign',
                'span' => 3,
                'queueName' => 'integrator:clean:adobe-campaign:queue',
                'secondsBack' => '1200',
                'secondsIntervals' => '5',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorInputDataManipulatorsBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-input-data-manipulators',
                'metric' => 'status',
                'title' => 'Manipulators',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorInputDataManipulatorsIntegrationBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-input-data-manipulators-integration',
                'metric' => 'status',
                'title' => 'Manipulators integration',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorDataCleanersBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-data-cleaners',
                'metric' => 'status',
                'title' => 'Cleaners',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorDataCleanersIntegrationBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-data-cleaners-integration',
                'metric' => 'status',
                'title' => 'Cleaners integration',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorDestinationWritersBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-destination-writers',
                'metric' => 'status',
                'title' => 'Destination writers',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorDestinationWritersIntegrationBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-destination-writers-integration',
                'metric' => 'status',
                'title' => 'Destination writers integration',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'integratorManipulatorsCommonBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'integrator',
                'job' => 'integrator-manipulators-common',
                'metric' => 'status',
                'title' => 'Manipulators COMMON',
                'refreshRate' => 5,
            ),
        ),

    ),
);
