<?php
/**
 * Config for rtm
 */
return array(
    'newRelic' => array(
        'headers' => array(
            'x-api-key' => '0116c7512e1efa28a39116312e9640edb90f1f52bb6ab30',
        ),
        'params' => array(
            'accountId' => '100366',
        ),
    ),
    'jenkins' => array(
        'params' => array(
            'baseUrl' => 'http://ci.vgnett.no/',
        ),
    ),
    'widgets' => array(
        array('id' => 'messages',
            'type' => 'messages',
            'params' => array(
                'dao' => 'events',
                'metric' => 'messages',
                'span' => 6,
                'title' => 'NotiFave',
                'limit' => 10,
            ),
        ),
        array('id' => 'notifaveMemory',
            'type' => 'number',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'memory',
                'appId' => '1716392',
                'title' => 'Memory',
                'valueSuffix' => 'MB',
            ),
        ),
        array('id' => 'notifaveErrorRate',
            'type' => 'error',
            'params' => array(
                'dao' => 'newRelic',
                'valueSuffix' => '%',
                'metric' => 'errorRate',
                'appId' => '1716392',
                'title' => 'Error Rate',
            ),
        ),

        array('id' => 'notifaveApdex',
            'type' => 'number',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'apdex',
                'appId' => '1716392',
                'title' => 'apdex',
            ),
        ),
        array('id' => 'notifaveCpuUsageGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'cpuUsage',
                'appId' => '1716392',
                'title' => 'CPU Usage',
                'valueSuffix' => '%',
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
            ),
        ),
        array('id' => 'notifaveAverageResponseTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'averageResponseTime',
                'appId' => '1716392',
                'title' => 'Average Response Time',
                'span' => 6,
                'valueSuffix' => 'ms',
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
            ),
        ),
        array('id' => 'notifaveBeRpm',
            'type' => 'graph',
            'params' => array(
                'span' => 6,
                'dao' => 'newRelic',
                'metric' => 'rpm',
                'appId' => '1716392',
                'title' => 'BE RPM',
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
            ),
        ),

        array('id' => 'notifaveFeBuildStat',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'NotiFave',
                'job' => 'NotiFave_-_frontend',
                'metric' => 'status',
                'title' => 'NotiFave FE Build',
            ),
        ),
        array('id' => 'notifaveServerBuildStat',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'NotiFave',
                'job' => 'NotiFave_-_server',
                'metric' => 'status',
                'title' => 'NotiFave Server Build',
            ),
        ),
        array('id' => 'notifaveServerV100BuildStat',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'NotiFave',
                'job' => 'Notifave_-_server-1.0.0',
                'metric' => 'status',
                'title' => 'NotiFave SERVER 1.0.0 Build',
            ),
        ),
        array('id' => 'notifaveServerV101BuildStat',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'NotiFave',
                'job' => 'Notifave_-_server-1.0.1',
                'metric' => 'status',
                'title' => 'NotiFave SERVER 1.0.1 Build',
            ),
        ),
    ),
);
