<?php
/**
 * Config for rtm
 */
return array(
    'theme' => 'dark', // (optional) default 'dark'
    'widgets' => array(
        array('id' => 'minmoteRenderRpmGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(nonNegativeDerivative(vg-render-01.tail-MinMote.counter-RequestsServed),5)',
                'title' => 'MinMote Render RPM',
                'span' => 3,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),
        array('id' => 'minmoteRenderAvgRspTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(vg-render-01.tail-MinMote.response_time-AvgResponseTime,5)',
                'valueSuffix' => 's',
                'title' => 'MinMote Render Avg Resp time',
                'span' => 3,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),

        array('id' => 'godtRenderRpmGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(nonNegativeDerivative(vg-render-01.tail-Godt.counter-RequestsServed),5)',
                'title' => 'Godt Render RPM',
                'span' => 3,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),
        array('id' => 'godtRenderAvgRspTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(vg-render-01.tail-Godt.response_time-AvgResponseTime,5)',
                'valueSuffix' => 's',
                'title' => 'Godt Render Avg Resp time',
                'span' => 3,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),

        array('id' => 'APTVRenderRpmGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(nonNegativeDerivative(vg-render-01.tail-APTV.counter-RequestsServed),5)',
                'title' => 'APTV Render RPM',
                'span' => 2,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),
        array('id' => 'APTVRenderAvgRspTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(vg-render-01.tail-APTV.response_time-AvgResponseTime,5)',
                'valueSuffix' => 's',
                'title' => 'APTV Render Avg Resp time',
                'span' => 2,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),

        array('id' => 'BTTVRenderRpmGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(nonNegativeDerivative(vg-render-01.tail-BTTV.counter-RequestsServed),5)',
                'title' => 'BTTV Render RPM',
                'span' => 2,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),
        array('id' => 'BTTVRenderAvgRspTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(vg-render-01.tail-BTTV.response_time-AvgResponseTime,5)',
                'valueSuffix' => 's',
                'title' => 'BTTV Render Avg Resp time',
                'span' => 2,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),

        array('id' => 'FVNTVRenderRpmGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(nonNegativeDerivative(vg-render-01.tail-FVNTV.counter-RequestsServed),5)',
                'title' => 'FVNTV Render RPM',
                'span' => 2,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),
        array('id' => 'FVNTVRenderAvgRspTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(vg-render-01.tail-FVNTV.response_time-AvgResponseTime,5)',
                'valueSuffix' => 's',
                'title' => 'FVNTV Render Avg Resp time',
                'span' => 2,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),

        array('id' => 'SATVRenderRpmGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(nonNegativeDerivative(vg-render-01.tail-SATV.counter-RequestsServed),5)',
                'title' => 'SATV Render RPM',
                'span' => 3,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),
        array('id' => 'SATVRenderAvgRspTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(vg-render-01.tail-SATV.response_time-AvgResponseTime,5)',
                'valueSuffix' => 's',
                'title' => 'SATV Render Avg Resp time',
                'span' => 3,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),

        array('id' => 'VGTVRenderRpmGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(nonNegativeDerivative(vg-render-01.tail-VGTV.counter-RequestsServed),5)',
                'title' => 'VGTV Render RPM',
                'span' => 3,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),
        array('id' => 'VGTVRenderAvgRspTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'graphite',
                'metric' => 'data',
                'target' => 'movingAverage(vg-render-01.tail-VGTV.response_time-AvgResponseTime,5)',
                'valueSuffix' => 's',
                'title' => 'VGTV Render Avg Resp time',
                'span' => 3,
                'from' => '-30min',
                'until' => '-0hour',
            ),
        ),
    ),
);
