<?php
/**
 * Config for rtm
 */
return [
    'theme' => ['tv', 'dark'],
    'newRelic' => [
        'headers' => [
            'x-api-key' => '0116c7512e1efa28a39116312e9640edb90f1f52bb6ab30',
        ],
        'params' => [
            'accountId' => '100366',
        ],
    ],
    'hipChat' => [
        'params' => [
            'auth_token' => 'd5e182ac9d356cbc72b9f9c2fc119f',
        ],
    ],
    'splunk' => [
        'params' => [
            'baseUrl' => 'https://splunk-01.int.vgnett.no:8089',
        ],
        'auth' => [
            'username' => 'stprtm',
            'password' => 'VTNAj7s8WErvR9uYhZeA',
        ],
    ],
    'jenkins' => [
        'params' => [
            'baseUrl' => 'http://ci.vgnett.no/',
        ],
    ],
    'widgets' => [
        ['id' => 'vektklubbApiSplunk500',
            'type' => 'alert',
            'params' => [
                'dao' => 'splunk',
                'metric' => 'Fivehundreds',
                'title' => 'Vektklubb API',
                'subtitle' => '500 errors in last 24h',
                'config' => [
                    'search' => 'search sourcetype=apache_access NOT(toolbox) host=vektklubb-api-0* status=500 | stats count latest(_time) as latestTime by url | sort -count | head 5',
                    'earliest_time' => '-24h',
                    'latest' => 'now',
                    'output_mode' => 'json',
                    'exec_mode' => 'oneshot',
                ],
                'span' => 3,
            ],
        ],
        ['id' => 'vektklubbApiCpuUsageGraph',
            'type' => 'graph',
            'params' => [
                'dao' => 'newRelic',
                'metric' => 'cpuUsage',
                'appId' => '8006994',
                'title' => 'CPU usage',
                'valueSuffix' => '%',
                'span' => 3,
                'beginDateTime' => '-60 minutes',
                'endDateTime' => 'now',
                'useThreshold' => 1,
                'thresholdComparator' => 'lowerIsBetter',
                'caution-value' => 150,
                'critical-value' => 175,
            ],
        ],
        ['id' => 'vektklubbApiMemory',
            'type' => 'incrementalGraph',
            'params' => [
                'dao' => 'newRelic',
                'metric' => 'memory',
                'appId' => '8006994',
                'title' => 'Memory',
                'span' => 3,
                'valueSuffix' => 'MB',
            ],
        ],
        ['id' => 'vektklubbApiAverageResponseTimeGraph',
            'type' => 'graph',
            'params' => [
                'dao' => 'newRelic',
                'metric' => 'averageResponseTime',
                'appId' => '8006994',
                'title' => 'AVG response time',
                'span' => 3,
                'valueSuffix' => 'ms',
                'beginDateTime' => '-60 minutes',
                'endDateTime' => 'now',
                'useThreshold' => 1,
                'thresholdComparator' => 'lowerIsBetter',
                'caution-value' => 200,
                'critical-value' => 250,
            ],
        ],


        ['id' => 'vektklubbApiBeRpm',
            'type' => 'graph',
            'params' => [
                'dao' => 'newRelic',
                'metric' => 'rpm',
                'appId' => '8006994',
                'span' => 3,
                'beginDateTime' => '-60 minutes',
                'endDateTime' => 'now',
                'title' => 'API RPM',
                'thresholdComparator' => 'lowerIsBetter',
                'caution-value' => 1000,
                'critical-value' => 1250,
            ],
        ],
        ['id' => 'vektklubbApiErrorRate',
            'type' => 'incrementalGraph',
            'params' => [
                'dao' => 'newRelic',
                'valueSuffix' => '%',
                'metric' => 'errorRate',
                'appId' => '8006994',
                'title' => 'Error Rate',
                'span' => 3,
                'thresholdComparator' => 'lowerIsBetter',
                'caution-value' => 1,
                'critical-value' => 5,
            ],
        ],
        ['id' => 'vektklubbApiApdex',
            'type' => 'number',
            'params' => [
                'dao' => 'newRelic',
                'metric' => 'apdex',
                'appId' => '8006994',
                'title' => 'apdex',
                'thresholdComparator' => 'higherIsBetter',
                'span' => 2,
            ],
        ],
        ['id' => 'vektklubbApiBuildStatus',
            'type' => 'build',
            'params' => [
                'dao' => 'jenkins',
                'view' => 'vektklubb',
                'job' => 'vektklubb-api',
                'metric' => 'status',
                'title' => 'Vektklubb API',
                'refreshRate' => 5,
                'span' => 2,
            ],
        ],
        ['id' => 'vektklubbApiBehatBuildStatus',
            'type' => 'build',
            'params' => [
                'dao' => 'jenkins',
                'view' => 'vektklubb',
                'job' => 'vektklubb-api-behat',
                'metric' => 'status',
                'title' => 'Vektklubb API Behat',
                'refreshRate' => 5,
                'span' => 2,
            ],
        ],


        // vektklubb.no website
        ['id' => 'vektklubbSiteSplunk500',
            'type' => 'alert',
            'params' => [
                'dao' => 'splunk',
                'metric' => 'Fivehundreds',
                'title' => 'Vektklubb Site',
                'subtitle' => '500 errors in last 24h',
                'config' => [
                    'search' => 'search sourcetype=apache_access NOT(toolbox) host=vektklubb-web-0* status>=500 | stats count latest(_time) as latestTime by url | sort -count | head 5',
                    'earliest_time' => '-24h',
                    'latest' => 'now',
                    'output_mode' => 'json',
                    'exec_mode' => 'oneshot',
                ],
                'span' => 3,
                'refreshRate' => 180,
            ],
        ],
        ['id' => 'vektklubbSiteCpuUsageGraph',
            'type' => 'graph',
            'params' => [
                'dao' => 'newRelic',
                'metric' => 'cpuUsage',
                'appId' => '172578',
                'title' => 'CPU usage',
                'valueSuffix' => '%',
                'span' => 3,
                'beginDateTime' => '-60 minutes',
                'endDateTime' => 'now',
                'useThreshold' => 1,
                'thresholdComparator' => 'lowerIsBetter',
                'caution-value' => 150,
                'critical-value' => 175,
            ],
        ],
        ['id' => 'vektklubbSiteMemory',
            'type' => 'incrementalGraph',
            'params' => [
                'dao' => 'newRelic',
                'metric' => 'memory',
                'appId' => '172578',
                'title' => 'Memory',
                'valueSuffix' => 'MB',
            ],
        ],
        ['id' => 'vektklubbSiteAverageResponseTimeGraph',
            'type' => 'graph',
            'params' => [
                'dao' => 'newRelic',
                'metric' => 'averageResponseTime',
                'appId' => '172578',
                'title' => 'AVG response time',
                'span' => 3,
                'valueSuffix' => 'ms',
                'beginDateTime' => '-60 minutes',
                'endDateTime' => 'now',
                'useThreshold' => 1,
                'thresholdComparator' => 'lowerIsBetter',
                'caution-value' => 300,
                'critical-value' => 400,
            ],
        ],
        ['id' => 'vektklubbSiteBeRpm',
            'type' => 'graph',
            'params' => [
                'dao' => 'newRelic',
                'metric' => 'rpm',
                'appId' => '172578',
                'span' => 3,
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
                'title' => 'Backend RPM',
                'thresholdComparator' => 'lowerIsBetter',
                'caution-value' => 750,
                'critical-value' => 1000,
            ],
        ],
        ['id' => 'foodErrorRate',
            'type' => 'incrementalGraph',
            'params' => [
                'dao' => 'newRelic',
                'valueSuffix' => '%',
                'metric' => 'errorRate',
                'appId' => '172578',
                'title' => 'Error Rate',
                'thresholdComparator' => 'lowerIsBetter',
                'caution-value' => 1,
                'critical-value' => 5,
            ],
        ],
        ['id' => 'vektklubbSiteBuildStatus',
            'type' => 'build',
            'params' => [
                'dao' => 'jenkins',
                'view' => 'vektklubb',
                'job' => 'vektklubb-website',
                'metric' => 'status',
                'title' => 'VK WWW',
                'refreshRate' => 5,
                'span' => 2,
            ],
        ],


        ['id' => 'vektklubbSiteDevelopBuildStatus',
            'type' => 'build',
            'params' => [
                'dao' => 'jenkins',
                'view' => 'vektklubb',
                'job' => 'vektklubb-website-develop',
                'metric' => 'status',
                'title' => 'VK WWW develop',
                'refreshRate' => 5,
                'span' => 2,
            ],
        ],
    ],
];
