<?php
/**
 * Config for rtm
 */
return array(
    'newRelic' => array(
        'headers' => array(
            'x-api-key' => '0116c7512e1efa28a39116312e9640edb90f1f52bb6ab30',
        ),
        'params' => array(
            'accountId' => '100366',
        ),
    ),
    'hipChat' => array(
        'params' => array(
            'auth_token' => 'd5e182ac9d356cbc72b9f9c2fc119f',
        ),
    ),
    'splunk' => array(
        'params' => array(
            'baseUrl' => 'https://mother.int.vgnett.no:8089',
        ),
        'auth' => array(
            'username' => 'wiskra',
            'password' => 'DopdeDey',
        ),
    ),
    'jenkins' => array(
        'params' => array(
            'baseUrl' => 'http://ci.vgnett.no/',
        ),
    ),
    'widgets' => array(
        array('id' => 'vektklubbApiSplunk500',
            'type' => 'alert',
            'params' => array(
                'dao' => 'splunk',
                'metric' => 'Fivehundreds',
                'title' => 'Vektklubb API',
                'subtitle' => '500 errors in last 24h',
                'config' => [
                    'search' => 'search sourcetype=apache_access NOT(toolbox) host=vektklubb-api-0* status=500 | stats count latest(_time) as latestTime by url | sort -count | head 5',
                    'earliest_time' => '-24h',
                    'latest' => 'now',
                    'output_mode' => 'json_cols',
                ],
                'span' => 6,
            ),
        ),
        array('id' => 'vektklubbApiCpuUsageGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'cpuUsage',
                'appId' => '3128405',
                'title' => 'CPU usage',
                'valueSuffix' => '%',
                'span' => 3,
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
            ),
        ),
        array('id' => 'vektklubbApiMemory',
            'type' => 'number',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'memory',
                'appId' => '3128405',
                'title' => 'Memory',
                'valueSuffix' => 'MB',
            ),
        ),
        array('id' => 'vektklubbApiAverageResponseTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'averageResponseTime',
                'appId' => '3128405',
                'title' => 'AVG response time',
                'span' => 3,
                'valueSuffix' => 'ms',
                'beginDateTime' => '-60 minutes',
                'endDateTime' => 'now',
            ),
        ),
        array('id' => 'vektklubbApiBeRpm',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'rpm',
                'appId' => '3128405',
                'span' => 3,
                'beginDateTime' => '-60 minutes',
                'endDateTime' => 'now',
                'title' => 'API RPM',
                'thresholdComparator' => 'higherIsBetter',
            ),
        ),
        array('id' => 'vektklubbApiErrorRate',
            'type' => 'error',
            'params' => array(
                'dao' => 'newRelic',
                'valueSuffix' => '%',
                'metric' => 'errorRate',
                'appId' => '3128405',
                'title' => 'Error Rate',
            ),
        ),
        array('id' => 'vektklubbApiApdex',
            'type' => 'number',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'apdex',
                'appId' => '3128405',
                'title' => 'apdex',
                'thresholdComparator' => 'higherIsBetter',
            ),
        ),
        array('id' => 'vektklubbApiBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'vektklubb',
                'job' => 'vektklubb-api',
                'metric' => 'status',
                'title' => 'Vektklubb API',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'vektklubbApiBehatBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'vektklubb',
                'job' => 'vektklubb-api-behat',
                'metric' => 'status',
                'title' => 'Vektklubb API Behat',
                'refreshRate' => 5,
            ),
        ),


        // vektklubb.no website
        array('id' => 'vektklubbSiteCpuUsageGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'cpuUsage',
                'appId' => '172578',
                'title' => 'CPU usage',
                'valueSuffix' => '%',
                'span' => 3,
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
            ),
        ),
        array('id' => 'vektklubbSiteMemory',
            'type' => 'number',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'memory',
                'appId' => '172578',
                'title' => 'Memory',
                'valueSuffix' => 'MB',
            ),
        ),
        array('id' => 'foodErrorRate',
            'type' => 'error',
            'params' => array(
                'dao' => 'newRelic',
                'valueSuffix' => '%',
                'metric' => 'errorRate',
                'appId' => '172578',
                'title' => 'Error Rate',
            ),
        ),
        array('id' => 'vektklubbSiteAverageResponseTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'averageResponseTime',
                'appId' => '172578',
                'title' => 'AVG response time',
                'span' => 3,
                'valueSuffix' => 'ms',
                'beginDateTime' => '-60 minutes',
                'endDateTime' => 'now',
            ),
        ),
        array('id' => 'vektklubbSiteBeRpm',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'rpm',
                'appId' => '172578',
                'span' => 3,
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
                'title' => 'Backend RPM',
                'thresholdComparator' => 'higherIsBetter',
            ),
        ),
        array('id' => 'vektklubbSiteBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'vektklubb',
                'job' => 'vektklubb-website',
                'metric' => 'status',
                'title' => 'VK WWW',
                'refreshRate' => 5,
            ),
        ),

        array('id' => 'vektklubbSiteSplunk500',
            'type' => 'alert',
            'params' => array(
                'dao' => 'splunk',
                'metric' => 'Fivehundreds',
                'title' => 'Vektklubb Site',
                'subtitle' => '500 errors in last 24h',
                'config' => [
                    'search' => 'search sourcetype=apache_access NOT(toolbox) host=vektklubb-web-0* status>=500 | stats count latest(_time) as latestTime by url | sort -count | head 5',
                    'earliest_time' => '-24h',
                    'latest' => 'now',
                    'output_mode' => 'json_cols',
                ],
                'span' => 6,
            ),
        ),
        array('id' => 'vektklubbSiteDevelopBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'vektklubb',
                'job' => 'vektklubb-website-develop',
                'metric' => 'status',
                'title' => 'VK WWW develop',
                'refreshRate' => 5,
            ),
        ),
        array('id' => 'vektklubbSiteDevelopDeployBuildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'vektklubb',
                'job' => 'vektklubb-website-develop',
                'metric' => 'status',
                'title' => 'VK develop deploy',
                'refreshRate' => 5,
            ),
        ),
    )
);
