<?php
/**
 * Config for rtm
 */
return array(
    'newRelic' => array(
        'headers' => array(
            'x-api-key' => '0116c7512e1efa28a39116312e9640edb90f1f52bb6ab30',
        ),
        'params' => array(
            'accountId' => '100366',
        ),
    ),
    'widgets' => array(
        array('id' => 'messages',
            'type' => 'messages',
            'params' => array(
                'dao' => 'events',
                'metric' => 'messages',
                'span' => 6,
                'title' => 'VGTV',
                'limit' => 10,
            ),
        ),
        array('id' => 'vgtvMemory',
            'type' => 'number',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'memory',
                'appId' => '53968',
                'title' => 'MEMORY',
                'valueSuffix' => 'MB',
            ),
        ),
        array('id' => 'vgtvApdex',
            'type' => 'numberWithNewRelicThreshold',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'apdex',
                'appId' => '53968',
                'title' => 'Apdex',
                'thresholdComparator' => 'higherIsBetter',
            ),
        ),
        array('id' => 'vgtvErrorRate',
            'type' => 'error',
            'params' => array(
                'dao' => 'newRelic',
                'valueSuffix' => '%',
                'metric' => 'errorRate',
                'appId' => '53968',
                'title' => 'ERROR RATE',
                'thresholdComparator' => 'lowerIsBetter',
            ),
        ),

        array('id' => 'vgtvCpuUsageGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'cpuUsage',
                'appId' => '53968',
                'title' => 'CPU USAGE',
                'valueSuffix' => '%',
                'span' => 6,
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
                'span' => 3,
            ),
        ),
        array('id' => 'vgtvAverageResponseTimeGraph',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'averageResponseTime',
                'appId' => '53968',
                'title' => 'Average response time',
                'span' => 6,
                'valueSuffix' => 'ms',
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
                'span' => 3,
            ),
        ),
        array('id' => 'vgtvBeRpm',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'rpm',
                'appId' => '53968',
                'span' => 6,
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
                'title' => 'Backend RPM',
                'span' => 3,
            ),
        ),
        array('id' => 'vgtvFeRpm',
            'type' => 'graph',
            'params' => array(
                'dao' => 'newRelic',
                'metric' => 'feRpm',
                'appId' => '53968',
                'span' => 6,
                'beginDateTime' => '-30 minutes',
                'endDateTime' => 'now',
                'title' => 'Frontend RPM',
                'span' => 3,
            ),
        ),

        array('id' => 'Stp_library-buildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'Stp_library',
                'metric' => 'status',
                'title' => 'STP LIB BUILD',
            ),
        ),
        array('id' => 'VGTV-live-selenium',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV-live-selenium',
                'metric' => 'status',
                'title' => 'VGTV LIVE SELENIUM',
            ),
        ),
        array('id' => 'VGTV-stage-selenium',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV-stage-selenium',
                'metric' => 'status',
                'title' => 'VGTV STAGE SELENIUM',
            ),
        ),
        array('id' => 'VGTV_admin-buildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV_admin',
                'metric' => 'status',
                'title' => 'VGTV ADMIN BUILD',
            ),
        ),
        array('id' => 'VGTV_admin_production',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV_admin_production',
                'metric' => 'status',
                'title' => 'VGTV ADMIN PROD BUILD',
            ),
        ),
        array('id' => 'VGTV_api-buildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV_api',
                'metric' => 'status',
                'title' => 'VGTV API BUILD',
            ),
        ),
        array('id' => 'VGTV_api_production',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV_api_production',
                'metric' => 'status',
                'title' => 'VGTV API PROD BUILD',
            ),
        ),
        array('id' => 'VGTV_backend',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV_backend',
                'metric' => 'status',
                'title' => 'VGTV BACKEND BUILD',
            ),
        ),
        array('id' => 'VGTV_front-end',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV_front-end',
                'metric' => 'status',
                'title' => 'VGTV FRONTEND BUILD',
            ),
        ),
        array('id' => 'VGTV_front-end-js-buildStatus',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV_front-end-js',
                'metric' => 'status',
                'title' => 'VGTV FRONTEND JS BUILD',
            ),
        ),
        array('id' => 'VGTV_front-end_production',
            'type' => 'build',
            'params' => array(
                'dao' => 'jenkins',
                'view' => 'VGTV',
                'job' => 'VGTV_front-end_production',
                'metric' => 'status',
                'title' => 'VGTV FRONTEND PROD BUILD',
            ),
        ),
    ),
);
