<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/dashboard.css')
//        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>
    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

</head>
<body>
<div class="container">
    <div class="row-fluid">
        <?php echo $this->content; ?>
    </div>
    <!--            <div id="testDiv"></div>-->

    <!--            <script>-->
    <!--                var testDiv = $('#testDiv');-->
    <!--                var oldValueHash = '';-->
    <!---->
    <!--                (function poll() {-->
    <!--                    $.ajax({-->
    <!--                    url: "/resources/rtm/vgtvRpm" + oldValueHash,-->
    <!--                    success: function (data) {-->
    <!--                        testDiv.text(data.data);-->
    <!--                        oldValueHash = "/" + data.hash;-->
    <!--                        console.log(data);-->
    <!--                    },-->
    <!--                    dataType: "json",-->
    <!--                    complete: poll,-->
    <!--                    timeout: 100000 });-->
    <!--                })();-->
    <!--            </script>-->


</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
