<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('STP Real Time Monitor'); ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php
    if ($this->theme) {
        $this->headLink()->prependStylesheet($this->basePath() . '/css/themes/' . $this->theme . '.css');
    }
    echo $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/dashboard.css')
        ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
        ->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:300italic,300,400italic,400,600italic,600,700italic,700,800italic,800')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>
    <!-- Scripts -->
    <script type="text/javascript">
        var baseUrl = <?php echo '"' . $this->basePath('/') . '"'; ?>;
    </script>
    <?php
    $jsAssets = $this->headScript();

    if (is_array($this->widgetTypes)) {
        foreach ($this->widgetTypes as $widgetType) {
            $jsAssets->prependFile($this->basePath() . '/js/widget/' . $widgetType . '.js');
        }

        $jsAssets->prependFile($this->basePath() . '/js/Dashboard.js')
            ->prependFile($this->basePath() . '/js/widget/Widget.js')
            ->prependFile($this->basePath() . '/js/highcharts/js/themes/dashboard.js')
            ->prependFile($this->basePath() . '/js/highcharts/js/highcharts.js')
            ->prependFile($this->basePath() . '/js/date.format.js');
    }

    echo $jsAssets
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ;
    ?>

</head>
<body id="dashboardBody">
<?php echo $this->content; ?>
<!-- /container -->
<?php echo $this->inlineScript()
    ->appendFile($this->basePath() . '/js/bootstrap.min.js')
    ->appendFile($this->basePath() . '/js/underscore-min.js')
    ->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->appendFile($this->basePath() . '/js/jquery.knob.js')
    ->appendFile($this->basePath() . '/js/jquery.blink.js')
    ->appendFile($this->basePath() . '/js/showdown.js')
    ->appendFile('//google-code-prettify.googlecode.com/svn/loader/run_prettify.js?skin=desert')
;
?>
</body>
</html>
